services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=homeworkdb
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=mypassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - users-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Api/Server/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=homeworkdb;Username=taskuser;Password=mypassword
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - users-network

volumes:
  postgres_data:

networks:
  users-network:
    driver: bridge
